### ISSUE TITLE
Decomposition of the Compilation and Optimization Process

### ISSUE THREAD

**Issue by maxkrieger** [penrose/penrose#148]
Steps in the compilation process can be decomposed more into individual pieces, and the compilation process can be decoupled from the optimization process. Right now, we envision the pieces communicating with each other with intermediate JSON data structures.

This will allow more steps in the process to be cachable and distributable across machines and services, which will improve scalability of online IDE services. This also allows more trivial steps in the process to be gradually ported over to the frontend (#35).

## TODO

- [ ] @wodeni make a system dependency diagram with all modules and top-level functions 
- [ ] Look into how to organize packages/sub-packages in Cabal/Hackage
- [ ] Message passing protocols, e.g. RabbitMQ, Protobuf...
