### ISSUE TITLE
Add strings to Substance

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#181]
The current raytracing domain models path regexes as strings. Therefore, we would need to add `String` to the Substance language as a primitive/built-in type. 
```
Scene S
Path p in S
String s := "LD*SE"

HasForm(p, s)

PathSample p1 := Sample(p)
PathSample p2 := Sample(p)
```
## Questions

- Should it, and can it be defined as a type in Element? (most likely not?)
- If not, can we build it into Substance? Once we have done so, how should Style handle it?
- Semi-related issue: #173 #175 (similar implementation strategy) 
- @hypotext: 
  - what happens when Style tries to match on an anonymous expression?
 
## TODOs

- [ ] Substance needs to support string literals
  - [x] RESOLVED: add `StrLit` as a part of `Expr` in Substance
  - [ ] update design paper as well
  - [x] parse strings
  - [ ] No anonymous literals when checking 
- [ ] Style needs to deal with (1) values and (2) values of String type
  - [ ] built-in field called `value`, similar to `text` 
  - [ ] never parse literals in Style selectors
- [x] Element needs to support string
  - As a built-in type `tconstructor String : type`

**Comment by wodeni** [comment]
Resolved in #185
