### ISSUE TITLE
Implement domain: Real Analysis

### ISSUE THREAD

**Issue by wodeni** [penrose/penrose#90]
This issue tracks the progress on implementing the real analysis domain using the new system with DSLL. 

## TODOs

- [x] Implement the language definition using DSLL
- [ ] Add missing computation/shapes/obj/constr to the system
- [ ] Examples from Jenna's spec:
    - [ ] Example 1
![image](https://user-images.githubusercontent.com/11740102/41741945-8d24c992-756a-11e8-8875-874711f25a31.png)
    - [ ] Example 2 
![image](https://user-images.githubusercontent.com/11740102/41741729-e90e9932-7569-11e8-95f8-c9e27ac85ce9.png)
   - [ ] Example 3
![keenan-real-analysis](https://user-images.githubusercontent.com/2762356/44744224-9dacc600-aad2-11e8-8904-ffcf464d3416.png)
   - [ ] Example 4
![screenshot 2018-09-11 23 29 45](https://user-images.githubusercontent.com/2762356/45400561-aa750200-b61a-11e8-8f85-5f5708d693ed.png)

## The DSLL

Now compiles in the current system:
```
tconstructor Set : type
tconstructor Reals : type
tconstructor Real : type
tconstructor Point : type
tconstructor Function : type
tconstructor Interval : type
tconstructor OpenInterval : type
tconstructor ClosedInterval : type
tconstructor LeftClopenInterval : type
tconstructor RightClopenInterval : type

vconstructor CreateInterval (left : Real, right : Real) : Interval
vconstructor CreateOpenInterval (left : Real, right : Real) : OpenInterval
vconstructor CreateClosedInterval (left : Real, right : Real) : ClosedInterval
vconstructor CreateLeftClopenInterval (left : Real, right : Real) : LeftClopenInterval
vconstructor CreateRightClopenInterval (left : Real, right : Real) : RightClopenInterval
vconstructor Pt (x : Real, y : Real) : Point

-- Subtyping relationships
Reals <: Set
Interval <: Set

OpenInterval <: Interval
ClosedInterval <: Interval
LeftClopenInterval <: Interval
RightClopenInterval <: Interval

-- Operators on intervals
operator union (I : Interval, J : Interval) : Interval
operator intersection (I : Interval, J : Interval)  : Interval

-- Operators on functions, points, and intervals
operator derivativeAtP (f : Function, p : Real) : Real
operator derivativeOverD (f : Function) : Function
operator integral (I : Interval, f : Function) : Real
operator apply (f : Function, p : Real) : Real

-- Predicates on intervals
predicate Bounded (i : Interval) : Prop
predicate LeftBounded (i : Interval) : Prop
predicate RightBounded (i : Interval) : Prop
predicate Unbounded (i : Interval) : Prop
predicate Compact (i : Interval) : Prop
predicate Disconnected (i : Interval) : Prop
predicate Degenerate (i : Interval) : Prop
predicate Empty (i : Interval) : Prop

-- Predicates on functions
predicate From (f : Function, domain : Set, codomain : Set) : Prop
predicate Continuous (f : Function) : Prop
predicate Discontinuous (f : Function) : Prop
predicate Differentiable (f : Function) : Prop
predicate Integrable (f : Function) : Prop
predicate Invertible (f : Function) : Prop
predicate Monotonic (f : Function) : Prop
predicate Decreasing (f : Function) : Prop
predicate Increasing (f : Function) : Prop

-- Predicates for containment
predicate In (x : Real, X : Set) : Prop
predicate In2 (p : Point, X : Set, Y : Set) : Prop
predicate Subset (X : Set, Y : Set) : Prop

-- Predicates on points
predicate LessThan (p1 : Real, p2 : Real) : Prop
predicate ClosedEnd (p : Real, I : Interval) : Prop
predicate OpenEnd (p : Real, I : Interval) : Prop

-- Prelude exports
--value RR : Reals

-- notation is ASCII only
-- kw NEW := OLD
--notation "f.domain" -> "Dom(f)"
-- TODO: flip rest
--notation "Cod(f)" := "f.codomain"
--notation "X Subset Y" := Subset(X, Y)

```

**Comment by wodeni** [comment]
Wrote the desugared version of the target Substance program according to the most recent DSLL, which passes the Substance parser and type checker:
https://github.com/penrose/penrose/blob/7bd8c4a90d1ae1d7589ca29c8a4b98070ca05f14/src/sub/reals.sub

```
--------------------------------------------------------------------------------
-- a, b, d, e, i, j, k, inf $\in$ $\mathbb{R}$

Reals RR
Real a
Real b
Real d
Real e
Real i
Real j
Real k
Real inf
In(a, RR)
In(b, RR)
In(d, RR)
In(e, RR)
In(i, RR)
In(j, RR)
In(k, RR)
In(inf, RR)

--------------------------------------------------------------------------------
-- b < k
LessThan(b, k)

--------------------------------------------------------------------------------
-- A := [a, b] $\subseteq$ $\mathbb{R}$
-- J := [d, e) $\subseteq$ $\mathbb{R}$
-- I := (i, j) $\subseteq$ $\mathbb{R}$
-- K := (k, inf) $\subseteq$ $\mathbb{R}$
ClosedInterval A
LeftClopenInterval J
OpenInterval I
OpenInterval K
A := CreateClosedInterval(a, b)
J := CreateLeftClopenInterval(d, e)
I := CreateOpenInterval(i, j)
K := CreateOpenInterval(k, inf)
Subset(A, RR)
Subset(J, RR)
Subset(I, RR)
Subset(K, RR)


--------------------------------------------------------------------------------
--  f : A $\rightarrow$ $\mathbb{R}$
--  Differentiable(f)
Function f
From(f, A, RR)
Differentiable(f)

--------------------------------------------------------------------------------
--  U := (J $\cup$ I) $\subseteq$ $\mathbb{R}$
--  h : U $\rightarrow$ $\mathbb{R}$
--  Discontinuous(h)
Interval U
U := union(J, I)
Function h
From(h, U, RR)
Discontinuous(h)


--------------------------------------------------------------------------------
--  l $\in$ A
--  fl := f(l)
--  p2 := Pt(l, fl)
Real l
In(l, A)
Real fl
fl := apply(f, l)
Point p2
p2 := Pt(l, fl)

--------------------------------------------------------------------------------
--  dfl := f'(l)
--  ih := $\int$_{J}(h)
Real dfl
dfl := derivativeAtP(f, l)
Real ih
ih  := integral(J, h)

```

**Comment by maxkrieger** [comment]
this is probably done?

**Comment by wodeni** [comment]
Yep, this domain is currently archived and we won’t come back to it soon. Closing
